# docker-compose file
#
# This file used to start nodes and monitor API from docker images.
# Monitor API used to get and send node's infomations to another server.
# Each node corresponds to an monitor API.
#
# Node 
#     - volumes: Puts configuration files to the local folder and corresponds to a container folder
#                The configuration file used by command 'start -c' likes 'node start -c /go-seele/config/node1.json'
#                There has some files in 'node_config' folder
#     - command: Start the node with an configuration file.
#     - ipv4_address: Fixed ip address in local area network
#
# monitor-api
#     - volumes: The configuration file in the container named 'app.conf' and must be put in /monitor-api
#                There has some files in 'monitor_api_config' folder
#     - RPCURL:  In 'app.conf', the address is set to the node's ipv4_address which you wants to link to.

version: '2'

services:
  #==============================================
  # node1 and monitor
  node1:
    image: webbergao/go-seele:latest
    # this node used to response rpc calls through those prots
    ports: 
      - "2525:55027" # rpc
      - "2526:65027" # http
    # external config file from this valume
    volumes:
      - /Volumes/work/go/src/github.com/seeleteam/deployment/node_config:/go-seele/config:ro
    # start node with config file
    command:
      node start -c /go-seele/config/node1.json
    networks:
      seele-testnet:
        # fixd ip address in test net
        ipv4_address: 172.32.128.11

  monitor-api-1:
    image: webbergao/monitor-api:latest
    # external config file from this valume
    volumes:
      - /Volumes/work/go/src/github.com/seeleteam/deployment/monitor_api_config/app1.conf:/monitor-api/app.conf:ro
    depends_on:
      - node1
    networks:
      seele-testnet:
        ipv4_address: 172.32.128.51

  #==============================================
  node2:
    image: webbergao/go-seele:latest
    # external config file from this volume
    volumes:
      - /Volumes/work/go/src/github.com/seeleteam/deployment/node_config:/go-seele/config:ro
 
    # start node with config file
    command:
      node start -c /go-seele/config/node2.json
    networks:
      seele-testnet:
        # fixd ip address in test net
        ipv4_address: 172.32.128.12

  monitor-api-2:
    image: webbergao/monitor-api:latest
    # external config file from this valume
    volumes:
      - /Volumes/work/go/src/github.com/seeleteam/deployment/monitor_api_config/app2.conf:/monitor-api/app.conf:ro
    depends_on:
      - node2
    networks:
      seele-testnet:
        ipv4_address: 172.32.128.52


networks:
  seele-testnet:
    ipam:
      config:
        - subnet: 172.32.0.0/16
          ip_range: 172.38.5.0/24
